### PR TITLE
RFC – First draft of SCSS linting rules

### PR DESCRIPTION
**Pull request by gvn**
This is my first attempt at defining our comprehensive list of rules for [sass-lint](https://github.com/sasstools/sass-lint).

Consider this PR a request for comments and discussion. Commenting inline on the `.sass-lint.yml` rules is probably easiest.

**Also:** Keep in mind that it's always easier to relax rules later than to add them!

### CODE REVIEW

**Comment by gvn** [comment]
CC: @simonwex @alanmoo @alicoding @mmmavis @ScottDowne @vazquez @flukeout @Pomax

Again, please @ mention anyone I may have forgotten!

**Comment by gvn** [comment]
Here's documentation for what all the rules mean:

https://github.com/sasstools/sass-lint/tree/develop/docs/rules

**Comment by flukeout** [comment]
@gvn is there a sample stylesheet somewhere that includes a lot of this proposed formatting? Pretty hard to comment on this stuff without seeing something more tangible.

**Comment by gvn** [comment]
It'd be pretty difficult to do that. I'd encourage everyone who cares strongly to [read the rules](https://github.com/sasstools/sass-lint/tree/develop/docs/rules) as they all contain examples.

As I mentioned, it's always easier to relax things later than add them. If any rule starts to feel overly restrictive we can always revise it or remove it entirely. :+1:

**Comment by gvn** [comment]
Also, once we start using these rules I'd recommend that everyone install a plugin in their editor-of-choice that can read the RC. That way you get immediate feedback as you write your code instead of getting hit with a bunch of errors all at once.

In Atom, for instance, you can install  `linter` and `linter-sass-lint` to get something like this:

screen shot 2016-02-12 at 1 57 56 pm

**Comment by gvn** [comment]
@flukeout We're using this set of rules in Foxlight, so if you want an idea of how it looks in practice you can check out our SCSS here: 

https://github.com/mozilla/foxlight/tree/master/src/scss

**Comment by gvn** [comment]
Ok I did some tweaks based on @alanmoo 's feedback. 

If no one else has any feedback I'd like to get this merged soon. :+1:

**Comment by alanmoo** [comment]
🤗

**Pull request merged**
